// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace FilosofeaData.Models
{
    [Table("Autores_Categorias")]
    public partial class AutoresCategorias
    {
        [Key]
        [Column("idAutor")]
        public long IdAutor { get; set; }
        [Key]
        [Column("idAutorCategoria")]
        public int IdAutorCategoria { get; set; }

        [ForeignKey(nameof(IdAutorCategoria))]
        [InverseProperty(nameof(AutoresCategoriasTipos.AutoresCategorias))]
        public virtual AutoresCategoriasTipos IdAutorCategoriaNavigation { get; set; }
        [ForeignKey(nameof(IdAutor))]
        [InverseProperty(nameof(Autores.AutoresCategorias))]
        public virtual Autores IdAutorNavigation { get; set; }
    }
}