// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace FilosofeaData.Models
{
    [Table("Autores_Categorias_Tipos")]
    public partial class AutoresCategoriasTipos
    {
        public AutoresCategoriasTipos()
        {
            AutoresCategorias = new HashSet<AutoresCategorias>();
            InverseIdAutorCategoriaPadreNavigation = new HashSet<AutoresCategoriasTipos>();
        }

        [Key]
        [Column("idAutorCategoria")]
        public int IdAutorCategoria { get; set; }
        [StringLength(155)]
        public string AutorCategoria { get; set; }
        [Column("idAutorCategoriaPadre")]
        public int? IdAutorCategoriaPadre { get; set; }

        [ForeignKey(nameof(IdAutorCategoriaPadre))]
        [InverseProperty(nameof(AutoresCategoriasTipos.InverseIdAutorCategoriaPadreNavigation))]
        public virtual AutoresCategoriasTipos IdAutorCategoriaPadreNavigation { get; set; }
        [InverseProperty("IdAutorCategoriaNavigation")]
        public virtual ICollection<AutoresCategorias> AutoresCategorias { get; set; }
        [InverseProperty(nameof(AutoresCategoriasTipos.IdAutorCategoriaPadreNavigation))]
        public virtual ICollection<AutoresCategoriasTipos> InverseIdAutorCategoriaPadreNavigation { get; set; }
    }
}