// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace FilosofeaData.Models
{
    public partial class Autores
    {
        public Autores()
        {
            AutoresCategorias = new HashSet<AutoresCategorias>();
            EntradasAutores = new HashSet<EntradasAutores>();
            Obras = new HashSet<Obras>();
        }

        [Key]
        [Column("idAutor")]
        public long IdAutor { get; set; }
        [StringLength(55)]
        public string Nombre { get; set; }
        [StringLength(155)]
        public string Pseudonimo { get; set; }
        [Column(TypeName = "date")]
        public DateTime? FechaNacimiento { get; set; }
        [Column(TypeName = "date")]
        public DateTime? FechaFallecimiento { get; set; }
        [Column("fhCreacion", TypeName = "datetime")]
        public DateTime FhCreacion { get; set; }

        [InverseProperty("IdAutorNavigation")]
        public virtual ICollection<AutoresCategorias> AutoresCategorias { get; set; }
        [InverseProperty("IdAutorNavigation")]
        public virtual ICollection<EntradasAutores> EntradasAutores { get; set; }
        [InverseProperty("IdAutorNavigation")]
        public virtual ICollection<Obras> Obras { get; set; }
    }
}