// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace FilosofeaData.Models
{
    [Table("Entradas_Estados")]
    public partial class EntradasEstados
    {
        public EntradasEstados()
        {
            Entradas = new HashSet<Entradas>();
        }

        [Key]
        [Column("idEstadoEntrada")]
        public int IdEstadoEntrada { get; set; }
        [StringLength(155)]
        public string Descripcion { get; set; }

        [InverseProperty("IdEstadoEntradaNavigation")]
        public virtual ICollection<Entradas> Entradas { get; set; }
    }
}