// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace FilosofeaData.Models
{
    [Table("Entradas_Categorias_Tipos")]
    public partial class EntradasCategoriasTipos
    {
        public EntradasCategoriasTipos()
        {
            EntradasCategorias = new HashSet<EntradasCategorias>();
            InverseIdEntradaCategoriaPadreNavigation = new HashSet<EntradasCategoriasTipos>();
        }

        [Key]
        [Column("idEntradaCategoria")]
        public int IdEntradaCategoria { get; set; }
        [StringLength(155)]
        public string Categoria { get; set; }
        [Column("idEntradaCategoriaPadre")]
        public int? IdEntradaCategoriaPadre { get; set; }

        [ForeignKey(nameof(IdEntradaCategoriaPadre))]
        [InverseProperty(nameof(EntradasCategoriasTipos.InverseIdEntradaCategoriaPadreNavigation))]
        public virtual EntradasCategoriasTipos IdEntradaCategoriaPadreNavigation { get; set; }
        [InverseProperty("IdEntradaCategoriaNavigation")]
        public virtual ICollection<EntradasCategorias> EntradasCategorias { get; set; }
        [InverseProperty(nameof(EntradasCategoriasTipos.IdEntradaCategoriaPadreNavigation))]
        public virtual ICollection<EntradasCategoriasTipos> InverseIdEntradaCategoriaPadreNavigation { get; set; }
    }
}