// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace FilosofeaData.Models
{
    public partial class Entradas
    {
        public Entradas()
        {
            EntradasAutores = new HashSet<EntradasAutores>();
            EntradasCategorias = new HashSet<EntradasCategorias>();
        }

        [Key]
        [Column("idEntrada")]
        public long IdEntrada { get; set; }
        [StringLength(155)]
        public string Titulo { get; set; }
        [StringLength(1555)]
        public string Texto { get; set; }
        [Column("fhEntrada", TypeName = "datetime")]
        public DateTime FhEntrada { get; set; }
        [Column("HL1")]
        [StringLength(255)]
        public string Hl1 { get; set; }
        [Column("HL2")]
        [StringLength(255)]
        public string Hl2 { get; set; }
        [Column("idUsuario")]
        public int? IdUsuario { get; set; }

        [ForeignKey(nameof(IdUsuario))]
        [InverseProperty(nameof(Usuarios.Entradas))]
        public virtual Usuarios IdUsuarioNavigation { get; set; }
        [InverseProperty("IdEntradaNavigation")]
        public virtual ICollection<EntradasAutores> EntradasAutores { get; set; }
        [InverseProperty("IdEntradaNavigation")]
        public virtual ICollection<EntradasCategorias> EntradasCategorias { get; set; }
    }
}