// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace FilosofeaData.Models
{
    [Table("Entradas_Categorias")]
    public partial class EntradasCategorias
    {
        [Key]
        [Column("idEntrada")]
        public long IdEntrada { get; set; }
        [Key]
        [Column("idEntradaCategoria")]
        public int IdEntradaCategoria { get; set; }

        [ForeignKey(nameof(IdEntradaCategoria))]
        [InverseProperty(nameof(EntradasCategoriasTipos.EntradasCategorias))]
        public virtual EntradasCategoriasTipos IdEntradaCategoriaNavigation { get; set; }
        [ForeignKey(nameof(IdEntrada))]
        [InverseProperty(nameof(Entradas.EntradasCategorias))]
        public virtual Entradas IdEntradaNavigation { get; set; }
    }
}