// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace FilosofeaData.Models
{
    [Table("Entradas_Autores")]
    public partial class EntradasAutores
    {
        [Key]
        [Column("idEntrada")]
        public long IdEntrada { get; set; }
        [Key]
        [Column("idAutor")]
        public long IdAutor { get; set; }

        [ForeignKey(nameof(IdAutor))]
        [InverseProperty(nameof(Autores.EntradasAutores))]
        public virtual Autores IdAutorNavigation { get; set; }
        [ForeignKey(nameof(IdEntrada))]
        [InverseProperty(nameof(Entradas.EntradasAutores))]
        public virtual Entradas IdEntradaNavigation { get; set; }
    }
}