// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace FilosofeaData.Models
{
    [Table("Obras_Categorias_Tipos")]
    public partial class ObrasCategoriasTipos
    {
        public ObrasCategoriasTipos()
        {
            InverseIdObraCategoriaPareNavigation = new HashSet<ObrasCategoriasTipos>();
            ObrasCategorias = new HashSet<ObrasCategorias>();
        }

        [Key]
        [Column("idObraCategoria")]
        public int IdObraCategoria { get; set; }
        [StringLength(155)]
        public string ObraCategoria { get; set; }
        [Column("idObraCategoriaPare")]
        public int? IdObraCategoriaPare { get; set; }

        [ForeignKey(nameof(IdObraCategoriaPare))]
        [InverseProperty(nameof(ObrasCategoriasTipos.InverseIdObraCategoriaPareNavigation))]
        public virtual ObrasCategoriasTipos IdObraCategoriaPareNavigation { get; set; }
        [InverseProperty(nameof(ObrasCategoriasTipos.IdObraCategoriaPareNavigation))]
        public virtual ICollection<ObrasCategoriasTipos> InverseIdObraCategoriaPareNavigation { get; set; }
        [InverseProperty("IdObraCategoriaNavigation")]
        public virtual ICollection<ObrasCategorias> ObrasCategorias { get; set; }
    }
}