// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace FilosofeaData.Models
{
    public partial class Obras
    {
        public Obras()
        {
            ObrasCategorias = new HashSet<ObrasCategorias>();
        }

        [Key]
        [Column("idObra")]
        public long IdObra { get; set; }
        [StringLength(155)]
        public string Titulo { get; set; }
        public int? AnhoPublicacion { get; set; }
        [Column("idAutor")]
        public long? IdAutor { get; set; }

        [ForeignKey(nameof(IdAutor))]
        [InverseProperty(nameof(Autores.Obras))]
        public virtual Autores IdAutorNavigation { get; set; }
        [InverseProperty("IdObraNavigation")]
        public virtual ICollection<ObrasCategorias> ObrasCategorias { get; set; }
    }
}